export default function handler(req, res) {
  const songs = [
    "Crazy",
    "Caliber",
    "At the Speed of Light",
    "Clubstep",
    "Not  Like Us",
    "Sonic Blaster",
    "The Angel",
    "XO",
    "Blast Processing",
    "Fireflies",
    "Nuke Powder",
    "Freedom Dive",
    "Billie Jean",
    "Code Red",
    "Purgatori",
    "I Love Cock 2",
    "GGEZ",
    "Time Machine",
    "Cry For Me",
    "Jackpot",
    "BIKE",
    "Headrush",
    "-Killstealer",
    "Fly Away",
    "Flawless Wings of Yatagarasu",
    "(Phobos)'",
    "Shiawase (VIP)",
    "Iron God: Sakupen Hell Yes RMX",
    "Isolation",
    "Shape of You",
    "Sweater Weather",
    "Believer",
    "Señorita",
    "Happier",
    "The Real Slim Shady",
    "Destroy All Those Aboard The Haunted Ship",
    "Epilogue",
    "The Angel",
    "Dimension",
    "Thermodynamix",
    "Time Leaper",
    "Heartbeat",
    "House of Memories",
    "Life Goes On",
    "Animation Warrior Theme",
    "The Yanderes Puppet Show",
    "Every End...",
    "Stereo Madness",
    "nano love",
    "FACT",
    "あくあ色ぱれっと",
    "I'M A GURKEY TURKEY",
    "Granny's House"
  ];

  const artists = [
    "Dimrain47",
    "Creo",
    "awesomeme3600",
    "TheFatRat",
    "F-777",
    "Rukkus",
    "Waterflame",
    "dj-Nate",
    "Panda Eyes",
    "TheLivingTombstone",
    "TheLarpingTombstone",
    "YOASOBI",
    "Nighthawk22",
    "Camellia",
    "Frums",
    "cYsmix",
    "Six Impala",
    "MannyHeffley",
    "Minato Aqua",
    "Tokoyami Towa",
    "Kolkian",
    "Drake",
    "Kanye",
    "Kendrick Lamar",
    "Marshmello",
    "Ed Sheeran",
    "ParagonX9",
    "Envy",
    "dexarson",
    "ForeverBound",
    "Tanger",
    "Xtrullor",
    "lchavasse",
    "OcularNebula",
    "Tennobyte",
    "ColBreakz",
    "KawaiSprite",
    "hinkik",
    "Monstercat",
    "Tobu",
    "Bossfight",
    "Step",
    "Solkrieg",
    "Gls",
    "The Beatles",
    "DECO*27",
    "Michael Jackson",
    "Taylor Swift",
    "Eminem",
    "Nicki Manaj",
    "Justin Bieber",
    "FGTeeV",
    "Lanky Box"
  ];

  const randomSong = songs[Math.floor(Math.random() * songs.length)];
  const randomArtist = artists[Math.floor(Math.random() * artists.length)];

  res.setHeader("Content-Type", "text/plain");
  res.status(200).send(`${randomSong} by ${randomArtist}`);
}
